### ISSUE TITLE
function is never used: `main`

### ISSUE THREAD

**Issue by saghmrossi** [flycheck/flycheck-rust#10]
I'm not sure if this is something that's caused by an external tool or if it can be fixed from the code in this repository, but the `main` function is reported as "unused code". This is essentially a cosmetic issue, but it would be nice to have it fixed.

**Comment by lunaryorn** [comment]
@saghmrossi Well, generally that means that `flycheck-rust-crate-type` is wrong.  But I can't say why it's wrong, or fix that.  I'll need to see how your project layout looks like, etc.

**Comment by saghmrossi** [comment]
Does flycheck-rust only work with crates? I guess I thought I could just use a standalone rust file.

**Comment by lunaryorn** [comment]
Everything is a crate in Rust, even if it's just one file, so you'll have to set the crate type, even for sole files.

Besides, this is not really related to this extension.  If you only work with single rust files, you don't even need this.  Flycheck supports Rust out of the box, this extension just configures it for Cargo projects.

**Comment by saghmrossi** [comment]
Ah, I see. Sorry about the hassle, I'm just starting to learn Rust, so I guess I wasn't completely clear on the concept of a crate (I'll go back and read the documentation again). 

Thanks for clearing this up for me!

**Comment by lunaryorn** [comment]
@saghmrossi A crate is simply a compilation unit in Rust.  Every file—even if it's just one—is part of a Crate.  If your file has a `main` function, you need to tell Rust that it should compile an executable—by setting `flycheck-rust-crate-type` to `"bin"`.

**Comment by lunaryorn** [comment]
@saghmrossi Now that the confusion is resolved, can I close this issue?

**Comment by saghmrossi** [comment]
Oops, sorry, I didn't see your question until now. You can close the issue.

Sorry for the trouble!
