### ISSUE TITLE
Error for extern crate

### ISSUE THREAD

**Issue by Nuk9** [flycheck/flycheck-rust#12]
For example following code snippet:

    extern crate regex;   // on this line flycheck has error 'can't find crate for 'regex''
    fn main() {
    }

Actually I have already setup regex crate in Cargo.toml, dependencies section.
Is there a way to prevent flycheck-rust stop checking extern crate related lines?

**Comment by lunaryorn** [comment]
@Nuk9 Did you run `cargo build`?  Does the library exist in `target/debug/deps/`?

**Comment by mkpankov** [comment]
Last time I stumbled upon this, this was especially a ptoblem with crates, that are bundled with `rustc`. For example, using `term` from `crates.io` would emit "can't find crate; multiple candidates" error on `extern crate term`.

This was due to direct launch of `rustc`, as opposed to `cargo` running `rustc`, which supplies additional options to define proper dependencies paths.

Also, AFAIK, `cargo rustc` command was implemented - does `flycheck-rust` use it now or not yet?

**Comment by lunaryorn** [comment]
@mkpankov Uhm, we obviously have a different error here… I appreciate your input, but please let us focus on solving this specific issue to help @Nuk9 instead of discussing the general approach of how we check Rust code in Flycheck. Thanks you.

See #8 for ideas on how to use Cargo instead.

**Comment by Nuk9** [comment]
I found out the reason: I need to run flycheck-rust-setup. Running that function solved this problem.

**Comment by lunaryorn** [comment]
@Nuk9 Uhm, that's actually [part of the installation instructions](https://github.com/flycheck/flycheck-rust#installation).  Were these instructions somehow unclear to you?

**Comment by Nuk9** [comment]
@lunaryorn Sorry I didn't visit github page, just installed the package from MELPA and I'm new to flycheck. Seems this init style also applies to other flycheck modes (e.g. flycheck-haskell) so I suggest it is my problem.

**Comment by lunaryorn** [comment]
@Nuk9 Please try to read the documentation of new packages in future.

**Comment by tomjakubowski** [comment]
@nuk9 just in case you don't know, from `M-x package-list-packages`, you can select a package and hit `?` to see information about it. Many packages include a brief README-like description, and all MELPA packages at least should have an HTTP link to a package homepage where there's often usage documentation. 

You can also see this information for an installed package with `C-h P` (capitalized P).

**Comment by Nuk9** [comment]
@tomjakubowski Thank you! I will carefully read the documentation before firing an issue on github next time.

**Comment by lunaryorn** [comment]
@Nuk9 I've improved the commentary of Flycheck and Flycheck Rust a bit to make things more clear, hopefully.
