### ISSUE TITLE
"Checker rust returned non-zero exit code 101..." error

### ISSUE THREAD

**Issue by fitzgen** [flycheck/flycheck-rust#13]
I installed flycheck and flycheck-rust from melpa and every time I open a .rs file and enable flycheck-mode I get the following error:

```
Checker rust returned non-zero exit code 101, but no errors from output: error: Unrecognized option: 'parse-only'.

Checker definition probably flawed.
```

Any idea what's up?

**Comment by lunaryorn** [comment]
@fitzgen What's your Rust version?  And what's the output of `C-c ! C-c rust` in a Rust buffer?

**Comment by fitzgen** [comment]
rustc 1.3.0-nightly (8ce69e856 2015-07-31)

When attempting to `C-c ! C-c rust`, after the second `C-c`, this pops up in a new buffer:

```
-*- mode: compilation; default-directory: "~/src/oxischeme/src/" -*-
Compilation started at Sun Aug 16 11:21:52

rustc --parse-only /Users/fitzgen/src/oxischeme/src/eval.rs
error: Unrecognized option: 'parse-only'.

Compilation exited abnormally with code 101 at Sun Aug 16 11:21:52
```

**Comment by lunaryorn** [comment]
@fitzgen Uhm, what's your Flycheck version?!  Flycheck stopped to use that option two years ago!

**Comment by fitzgen** [comment]
That is very interesting...

I guess it is time to clean up my .emacs.d dir...

These things tend to accumulate a mess...
