### ISSUE TITLE
"Can't find crate" for extern (even after `cargo build`)

### ISSUE THREAD

**Issue by mgalgs** [flycheck/flycheck-rust#15]
I'm new to rust, so maybe I'm doing something silly, but I seem to be having troubles getting `flycheck-rust` to recognize any external dependencies whatsoever.  I've put together a minimal demo repo that shows the problem for a crates.io dependency as well as a local dependency: https://github.com/mgalgs/flycheck-rust-test

In `frsub/lib.rs` in that repo, I'm trying to extern a crate from crates.io which is present in my `Cargo.toml`, but flycheck-rust complains about not being able to find it (even after running `cargo build` from the `frsub` directory).

In `src/main.rs` in that repo, I'm trying to extern in the `frsub` crate by path (see `Cargo.toml` at the top-level).

What am I missing here?

**Comment by mkpankov** [comment]
@mgalgs it's the same as https://github.com/flycheck/flycheck-rust/issues/8

Currently Flycheck is unable to get proper search paths of crates which are used by Cargo.

**Comment by lunaryorn** [comment]
Closing as duplicate then.
