### ISSUE TITLE
problem with flycheck-rust and multirust

### ISSUE THREAD

**Issue by olsonjeffery** [flycheck/flycheck-rust#24]
Hello, I'm using emacs 24 on OSX. My rust toolchain uses multirust.

After going through the slog of diagnosing and properly configuring my exec-path so that cargo et al could be located. Anyways, after that I get this flycheck error when doing `flycheck-buffer` in a rust buffer:

```
Suspicious state from syntax checker rust-cargo: Checker rust-cargo returned non-zero exit code 1, but no errors from output: multirustproxy: need dirname

Checker definition probably flawed.
```

Curious if anyone has ran into this and how they fixed it.

Thanks in advance.

**Comment by lunaryorn** [comment]
@olsonjeffery What is "multirust"?

**Comment by olsonjeffery** [comment]
https://github.com/brson/multirust

```
A simple tool for managing multiple installations of the Rust toolchain. It replaces the standard Rust toolchain with components that dynamically choose between alternate implementations based on context.
```

**Comment by lunaryorn** [comment]
@olsonjeffery Well, yes, but how does it work?  

Presumably, there's a crucial setup step missing in your Emacs configuration, e.g. a missing environment variable, that's causing the error.  We'll need to find the missing step, but I don't know anything about "multirust", hence I'll need your help to help you :wink: (meta :joy:)

**Comment by olsonjeffery** [comment]
yeah it must've been some kind of environmental issue.

I paved my emacs setup and tried out spacemacs along with its rust layer and flycheck-rust works fine.

Cheers!
