### ISSUE TITLE
Running rustc with -Z no-trans disables some errors

### ISSUE THREAD

**Issue by mkpankov** [flycheck/flycheck-rust#26]
Passing -Z no-trans disables some errors. In particular, type size comparison done when checking if `std::mem::transmute` should be allowed is not performed.

See this example: https://is.gd/cnjaFI . When run locally with `-Z no-trans`, no errors are reported.

**Comment by fmdkdd** [comment]
Good to know.  Is there anything we can do on flycheck's end, or must we wait for an improvement to rustc or cargo?

**Comment by mkpankov** [comment]
I don't think there's anything we can do, except running `rustc` normally - w/o `-Z no-trans`. It has the downside of slowing down to the speed of usual compilation - which can be big.

**Comment by fmdkdd** [comment]
Looks like this PR will fix this issue with `-Z no-trans`: https://github.com/rust-lang/cargo/pull/3296.  I'm making a note here to come back and add `cargo check` to flycheck when it has landed.

**Comment by nrc** [comment]
I'm not sure that `cargo check` will fix this issue - since we still don't execute the trans phase, any error which is caught in that phase will still slip through.

**Comment by fmdkdd** [comment]
@nrc Oh.  I got the impression from [your comment](https://github.com/rust-lang/cargo/pull/3296#issuecomment-264079907) that `cargo check` was an improvement over passing `-Z no-trans` for exactly this issue.

Re-reading that comment, it seems it will still be an improvement over using `-Z no-trans`, even if it doesn't report errors in the trans phase.

Some day we'll be able to get *all* errors quickly.  Through the RLS, probably.

**Comment by nrc** [comment]
It is an improvement, but for a different issue - it works with syntax extensions/compiler plugins/build scripts. The RLS will use `cargo check`, so will still miss out on those trans errors. Perhaps someday we'll figure out how to check for them before trans...

**Comment by fmdkdd** [comment]
Closing since this `-Zno-trans` is now an error in Rust 1.19.
