### ISSUE TITLE
flycheck-rust-setup: Symbol's value as variable is void: \.targets

### ISSUE THREAD

**Issue by marcbowes** [flycheck/flycheck-rust#27]
Hi,

After upgrading I get this error when opening .rs files:

```
flycheck-rust-setup: Symbol's value as variable is void: \.targets
```

It seems the most recent commit introduced the code that is failing for me: https://github.com/flycheck/flycheck-rust/commit/a8f76ed51c97a4fef6bc558da18be744d18cd69e.

GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org

**Comment by marcbowes** [comment]
I downgraded to https://raw.githubusercontent.com/flycheck/flycheck-rust/e03c895ef1ce514f7cefcd86f10e6bde97ff1c73/flycheck-rust.el and the problem went away for me. Is there something on my system that is maybe incompatible? I see the commit message notes a newer version of seq than what I seem to have but the error happens on a line before seq is used.

**Comment by lunaryorn** [comment]
@marcbowes Oh, sorry, we forgot to add a dependency on `let-alist` in this code.  I didn't notice earlier because I'm using Emacs 25 where it's built-in.

Please upgrade once MELPA has built this package again in a couple of hours; the error should be gone then.

Please excuse this blunder of ours 😞

**Comment by marcbowes** [comment]
No problem. Thanks for the super speedy turnaround. I'll try manually do this while I wait for the release.

**Comment by marcbowes** [comment]
Hmm I already have that installed at at v1.0.4.

**Comment by marcbowes** [comment]
I manually applied your edit and things seem to work for me.

Thanks!
