### ISSUE TITLE
Can’t parse new error message format from Rust 1.12 nightly

### ISSUE THREAD

**Issue by andersk** [flycheck/flycheck-rust#31]
Rust 1.12 introduces a [new format for error messages and warnings](https://blog.rust-lang.org/2016/08/10/Shape-of-errors-to-come.html), and flycheck-rust will need to be taught how to parse it. Right now flycheck-rust shows no errors or warnings when used with Rust 1.12 nightly.

**Comment by fmdkdd** [comment]
Indeed, thank you for your report.

We have a PR over at flycheck/flycheck#1036 that uses the JSON error format to restore functionality for flycheck in nightly.  It just needs reviewing before merging.

In the meantime, you are welcome to try out that branch if you ache for flycheck highlights.  I've tested it on nightly and it worked, but I'd love more feedback.

**Comment by lunaryorn** [comment]
I'm closing this issue, in favour of flycheck/flycheck#1036.  Thank you for reporting it!
