### ISSUE TITLE
flycheck-rust can not run correctly

### ISSUE THREAD

**Issue by timzaak** [flycheck/flycheck-rust#33]
I use this configuration : https://github.com/rustcc/RustPrimer/issues/519 .
the racer can work correctly, but flycheck does noting. If is the configuration is wrong, or anything else?
my enviroment is :
OS:  mac OSX,
Emacs:  24.5
pacakges are all the newest.

**Comment by lunaryorn** [comment]
@timzaak Thank you for reporting this issue, but please put more effort in your issue reports.  This one isn't helpful.

Please elaborate what "does nothing" means.  Take the time and in detail describe the behaviour you see in contrast to the behaviour you expect.  Then please try to reproduce the issue in `emacs -Q` with only the relevant packages loaded.  If you are able to reproduce the issue in `emacs -Q` then please provide us with a recipe to reproduce the problem, including the source code on which syntax checking fails and the *minimal* configuration you used to reproduce the error.

Thank you.

**Comment by timzaak** [comment]
after  M-x flycheck-select-checker <RET> rust .it showes
![image](https://cloud.githubusercontent.com/assets/6149407/18054634/3e791f8c-6e37-11e6-9192-d4b406f570aa.png)
and the source  code is :
![image](https://cloud.githubusercontent.com/assets/6149407/18054667/5645e42e-6e37-11e6-8f76-2cb64948c824.png)

**Comment by lunaryorn** [comment]
Where's the `rust-cargo` syntax checker?  It's built into recent versions of Flycheck, and missing in your Emacs?

**Comment by impowski** [comment]
@lunaryorn I guess it can be closed because the only thing was needed is to run `U x` in after `M x package-list-packages` or `M x list-packages`. At least it worked for me because I thought that I had a brand new packages at first but then.
