### ISSUE TITLE
Getting couldn't read "src/main.rs": No such file or directory (os error 2)

### ISSUE THREAD

**Issue by simao** [flycheck/flycheck-rust#49]
`flycheck-rust` reports this error whenever I open a rust file.

The file `src/main.rs` exists and is the file I am currently opening. Do I miss some config here?

I am using only `rust-mode` and `flycheck-rust` from melpa, with:

```
(require 'sm-flycheck)

(add-hook 'rust-mode-hook 'flycheck-mode)
(add-hook 'flycheck-mode-hook #'flycheck-rust-setup)
(add-hook 'rust-mode-hook 'subword-mode)
```

Thanks

**Comment by fmdkdd** [comment]
Are you per chance on Windows?

**Comment by simao** [comment]
No, linux.

Am 11. Februar 2017 17:57:09 MEZ schrieb fmdkdd <notifications@github.com>:

**Comment by fmdkdd** [comment]
I cannot yet reproduce.  Can you give me the output of `flycheck-verify-setup` (`C-c ! v`)?  And maybe the steps to reproduce from a vanilla `emacs -Q`?

**Comment by simao** [comment]
Here is the output of flycheck-verify-setup:
https://gist.github.com/simao/7c63ff475667e1f2b94c9908e6f96fdb


With a vanilla emacs and after installing rust-mode and flycheck-rust
via melpa, I open the same file and I get a different error:


```

Suspicious state from syntax checker rust-cargo: Flycheck checker rust-
cargo returned non-zero exit code 101, but its output contained no
errors:    Compiling slave v0.1.0 (file:///home/simao/code/slave)
error: Could not compile `slave`.



To learn more, run the command again with --verbose.



Try installing a more recent version of rust-cargo, and please open a
bug report if the issue persists in the latest release.  Thanks!
```



Thanks!





On Sat, Feb 11, 2017, at 18:53, fmdkdd wrote:

> I cannot yet reproduce.  Can you give me the output of flycheck-verify-
> setup (C-c ! v)?  And maybe the steps to reproduce from a vanilla
> emacs -Q?
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/flycheck/flycheck-rust/issues/49#issuecomment-279163390

**Comment by fmdkdd** [comment]
Curious.  `flycheck-verify-setup` lists `rust-cargo` as unregistered, so it should not run.  Something in your config is defining `flycheck-checkers` before `flycheck` loads.  That's a first issue.

For the `emacs -Q` run, it looks like `cargo rustc` cannot compile your project.  What does `cargo rustc --verbose` returns if you run it manually in your project?

**Comment by simao** [comment]
Ok, indeed, I had an old flycheck-checkers config in  custom variables.
I removed it and now I get exactly the same message I get when I run
with `emacs -Q`.


I do not have rust-cargo installed, or at least I did not install it
explicitly.


Here's the output of `cargo rustc --verbose`:
https://gist.github.com/simao/631f8b06b109589a086ca1e270dea758


Simao





On Sat, Feb 11, 2017, at 19:45, fmdkdd wrote:

> Curious. flycheck-verify-setup lists rust-cargo as unregistered, so it
> should not run.  Something in your config is defining flycheck-
> checkers before flycheck loads.  That's a first issue.
> For the emacs -Q run, it looks like cargo rustc cannot compile your
> project.  What does cargo rustc --verbose returns if you run it
> manually in your project?
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/flycheck/flycheck-rust/issues/49#issuecomment-279166843

**Comment by fmdkdd** [comment]
Hmm so `cargo rustc --verbose` run does not report any error when run manually, but does when running through flycheck?

Can you report what `M-x flycheck-compile` does in the buffer visiting `src/main.rs`?  If prompted for a checker name, input `rust-cargo`.

`rust-cargo` is just the name of the rust checker Flycheck uses to call cargo.

**Comment by simao** [comment]
This is the output when I run flycheck-compile:



```

-*- mode: compilation; default-directory: "~/code/slave/src/" -*-

Compilation started at Sun Feb 12 00:42:45



cargo rustc --bin s --message-format\=json -- -Z no-trans -
L/home/simao/code/s/target/debug -L/home/simao/code/s/target/debug/deps
   Compiling s v0.1.0 (file:///home/simao/code/s)

error: Could not compile `s`.



To learn more, run the command again with --verbose.



Compilation exited abnormally with code 101 at Sun Feb 12 00:42:46

```



If I try running this command in the cli I get the same output,
but `cargo build` works fine, but it does show some code warnings,
dead code etc.








On Sun, Feb 12, 2017, at 00:39, fmdkdd wrote:

> Hmm so cargo rustc --verbose run does not report any error when run
> manually, but does when running through flycheck?
> Can you report what M-x flycheck-compile does in the buffer visiting
> src/main.rs?  If prompted for a checker name, input rust-cargo.
> rust-cargo is just the name of the rust checker Flycheck uses to
> call cargo.
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/flycheck/flycheck-rust/issues/49#issuecomment-279184253

**Comment by fmdkdd** [comment]
Okay, can you run manually in your project:

1. `cargo rustc --bin s --message-format=json --verbose -- -Z no-trans`
2. `cargo rustc --bin s --message-format=json --verbose`

And also let me know `rustc --version` and `cargo --version`?

**Comment by simao** [comment]
1. https://gist.github.com/simao/067703edc0ca6b2ff06dc7c7b0a4b776

2. https://gist.github.com/simao/1c72790b7ac685ed3e102ae0db18eb68



rustc 1.14.0

cargo 0.15.0-dev (298a0127 2016-12-20)





On Sun, Feb 12, 2017, at 11:29, fmdkdd wrote:

> Okay, can you run manually in your project:


>  1. cargo rustc --bin s --message-format=json --verbose -- -Z no-trans
>  2. cargo rustc --bin s --message-format=json --verbose
> And also let me know rustc --version and cargo --version?



> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/flycheck/flycheck-rust/issues/49#issuecomment-279209246

**Comment by fmdkdd** [comment]
Right!  So you are using Rust 1.14, and we recently moved to to require 1.15 (see flycheck/flycheck#1201).  Sorry for the inconvenience.

If you update to the latest stable Rust, it should work for you.  Sorry for the long back-and-forth.

**Comment by simao** [comment]
oh sorry I didn't see that. It works now, thanks!





On Sun, Feb 12, 2017, at 12:56, fmdkdd wrote:

> Right!  So you are using Rust 1.14, and we recently moved to to
> require 1.15 (see flycheck/flycheck#1201[1]).  Sorry for the
> inconvenience.
> If you update to the latest stable Rust, it should work for you.
> Sorry for the long back-and-forth.
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].
> 




Links:

  1. https://github.com/flycheck/flycheck/pull/1201
  2. https://github.com/flycheck/flycheck-rust/issues/49#issuecomment-279213544

**Comment by fmdkdd** [comment]
Good to know.  Happy hacking :)
