### ISSUE TITLE
Using log or getops crates reports "multple matching crates" error to be displayed

### ISSUE THREAD

**Issue by hugoduncan** [flycheck/flycheck-rust#5]
For some crates (at least `log` and `getopts`), declaring `extern crate getopts;` leads to the following errors displayed in flycheck:

```
Multiple matching crates for `getopts`
can't find crate for `getopts`
```

This seems to be caused by the existence of `log` and `getopts` library files in rustlib.

Cargo doesn't report the same errors when run directly, as it uses different rustc arguments to flycheck-rust (`-L dependency=…` and `--extern …=…`).

**Comment by mcobzarenco** [comment]
+1

**Comment by lunaryorn** [comment]
@hugoduncan Feel free to open a pull request to improve flycheck-rust.  I don't have the time to fix this issue currently, and I don't use Rust anymore.

**Comment by hugoduncan** [comment]
Unfortunately it doesn't seem like a trivial fix, and will probably involve updating the rust support in flycheck itself.  I can't see a way of doing it corrctly without parsing the `Cargo.toml` file.

**Comment by hugoduncan** [comment]
It seemed simplest just to invoke `cargo`. I started [flycheck-cargo](https://github.com/hugoduncan/flycheck-cargo).

**Comment by lunaryorn** [comment]
@hugoduncan Cargo would build the entire project to check a single file, wouldn't it?

**Comment by hugoduncan** [comment]
@lunaryorn Yes, and it definitely has speed issues.

**Comment by utkarshkukreti** [comment]
Would this help: https://github.com/rust-lang/cargo/pull/1225?

**Comment by lunaryorn** [comment]
@utkarshkukreti Probably, though a structured format would be better, i.e. JSON.

**Comment by lunaryorn** [comment]
Effectively blocked by https://github.com/rust-lang/cargo/pull/1434.

**Comment by lunaryorn** [comment]
Closing, in favour of #8
