### ISSUE TITLE
some benefit from "cargo check"?

### ISSUE THREAD

**Issue by z1mvader** [flycheck/flycheck-rust#51]
Is possible to improve flycheck-rust with the introduction of the command `cargo check` on rust 1.16?

**Comment by imadie** [comment]
that would be awesome

**Comment by fmdkdd** [comment]
Thanks for reminding me of this.  

We already pass `-Z no-trans` to rustc in Flycheck to avoid compiling binaries and taking too much time.   I suspect we won't see a significant improvement by using `cargo check`;  the only benefit would be to [support some advanced uses](https://github.com/rust-lang/cargo/pull/3296#issuecomment-264079907) that `-Z no-trans` did not.

**Comment by fmdkdd** [comment]
I just tested it, and `cargo check` [cannot currently check code](https://github.com/rust-lang/cargo/issues/3431) inside `#[cfg(test]`, so that would be a regression in functionality.  I think we better to stick to `-Z no-trans` until this is resolved at least.

**Comment by imadie** [comment]
Thanks, then I think we will wait :)

**Comment by fmdkdd** [comment]
Update: using `-Z` flags on stable [may soon be an error](https://github.com/rust-lang/rust/pull/41751), rather than a warning.  Thus, we will then have to migrate to `cargo check`.

However, at the moment `cargo check` still does not check unit tests, but [there is an ongoing PR](https://github.com/rust-lang/cargo/pull/4039).

**Comment by thejefflarson** [comment]
Hi, it is now an error in the rust version released [today](https://blog.rust-lang.org/2017/07/20/Rust-1.19.html).

I'll hold off on using 1.19 for now, as it looks like the upstream PR is still not merged https://github.com/rust-lang/rust/pull/41751 but it looks like a tricky one to fix without that. Thanks for flycheck-rust it is great!

**Comment by fmdkdd** [comment]
Argh!  Thanks for the heads-up.  Looks like we'll have to use `cargo check` without unit tests then.  I'll try to make a PR tomorrow.
