### ISSUE TITLE
Does not support emacs25

### ISSUE THREAD

**Issue by djanderson** [flycheck/flycheck-rust#58]
Emacs25 has seq 2.3 built-in, but you require "2.15". Since 15 > 3, flycheck-rust refuses to install. By changing `(seq "2.15")` to `(seq "2.3")`, I am able to manually install the package and it works fine.

**Comment by fmdkdd** [comment]
How do you install the package?  If I do `package-install` from MELPA, it installs `seq` 2.20 (the latest) from ELPA to satisfy the dependency.

(We might not need seq 2.15 in any case, but it shouldn't be an issue)

**Comment by djanderson** [comment]
Interesting, it looks like I dropped ELPA out of my init.el years ago and never had an issue running MELPA only until now, but I don't have any problem adding it back in so this solved the issue for me. Thanks!
