### ISSUE TITLE
Can’t find crates that Cargo got from crates.io

### ISSUE THREAD

**Issue by andersk** [flycheck/flycheck-rust#6]
In a Cargo project with a dependency on (say) the [num](https://crates.io/crates/num) crate, flycheck-rust reports “can't find crate for \`num\`” on the `extern crate num;` line.

```console
$ cat Cargo.toml
[package]
name = "foo"
version = "0.0.1"

[dependencies]
num = "*"

$ cat src/lib.rs
extern crate num;

$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling rustc-serialize v0.3.12
   Compiling libc v0.1.5
   Compiling log v0.3.1
   Compiling rand v0.3.7
   Compiling num v0.1.21
   Compiling foo v0.0.1 (file:///tmp/foo)
```

**Comment by andersk** [comment]
I guess this is probably the same underlying problem as #5.

**Comment by lunaryorn** [comment]
@andersk Can you should me the output of `find target` in your project directory?  I presume the layout of the build directory of Cargo changed.

Ultimately, though, we'll always suffer from issues like this, until we have a way to extract the build settings from Cargo itself.  See https://github.com/rust-lang/cargo/pull/1434.

**Comment by utkarshkukreti** [comment]
The `debug` build output is now stored in `/target/debug` instead of `/target`. This should work: https://gist.github.com/utkarshkukreti/d7e2016e72bb03af15eb

**Comment by andersk** [comment]
@utkarshkukreti: Yes, that’s exactly it.

**Comment by lunaryorn** [comment]
@andersk @utkarshkukreti Great, thanks.  I fixed the issue.
