### ISSUE TITLE
Option `Z` not accepted.

### ISSUE THREAD

**Issue by benreynwar** [flycheck/flycheck-rust#60]
rustc 1.23.0 (766bd11c8 2018-01-01)
cargo 0.24.0 (45043115c 2017-12-05)
I just installed flycheck-rust from melpa today.
I'm getting the following error message when the syntax-checker runs:

Suspicious state from syntax checker rust-cargo: Checker rust-cargo returned non-zero exit code 101, but no errors from output:    Compiling hello v0.1.0 (file:///home/ben/Code/rust/hello)
error: the option `Z` is only accepted on the nightly compiler

error: Could not compile `hello`.

To learn more, run the command again with --verbose.

Checker definition probably flawed.

**Comment by fmdkdd** [comment]
You should update the `flycheck` package proper.

**Comment by benreynwar** [comment]
That fixed it.  Thanks!
