### ISSUE TITLE
unknown debugging option no-trans

### ISSUE THREAD

**Issue by cocodrino** [flycheck/flycheck-rust#66]
Hi guys, Ive just installed the rust layer on spacemacs, racer works ok but I'm getting  "unknown debugging option no-trans" on my flycheck in the first line of my code...

rust and flycheck seems ok
```
Syntax checkers for buffer main.rs in rust-mode:

  rust-cargo
    - may enable:  yes
    - predicate:   t
    - executable:  Found at /home/yo/.cargo/bin/cargo
    - Cargo.toml:  Found
    - Crate type:  bin
    - Binary name: rustD

  rust
    - may enable: yes
    - predicate:  t
    - executable: Found at /home/yo/.cargo/bin/rustc

Flycheck Mode is enabled. Use SPC u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 31snapshot (package: 20170415.1006)
Emacs version:    25.3.1
System:           x86_64-pc-linux-gnu
Window system:    x
```

what could be the problem here???

thank you so much guys, any question please let me know...

**Comment by fmdkdd** [comment]
> Flycheck version: 31snapshot (package: 20170415.1006)

Try updating the `flycheck` and `flycheck-rust` packages.

**Comment by ParityB1t** [comment]
newest version of rust just updated to change the `no-trans` option to `no-codegen`

See [https://github.com/w0rp/ale/pull/1806](url)

I tried compiling with no-trans using `flycheck-compile` and on term: 
```
cargo rustc --bin hello_world -- -Z no-trans -Z unstable-options --error-format\=json --test

{"message":"unknown debugging option: `no-trans`","code":null,"level":"error","spans":[],"children":[],"rendered":"error: unknown debugging option: `no-trans`\n\n"}
error: Could not compile `hello_world`.
```

But changing it to `no-codegen` on term works :smile: 

```
cargo rustc --bin hello_world -- -Z no-codegen -Z unstable-options --error-format\=json --test
Finished dev [unoptimized + debuginfo] target(s) in 0.36s
```

Trying to get a grips of lisp to do a pull request and change it to `no-codegen` on flycheck too.

**Comment by fmdkdd** [comment]
@ParityB1t Thanks, but we cannot use `-Z no-codegen` on stable, can we?  So I'd rather go with https://github.com/flycheck/flycheck/pull/1501 instead.

I'm closing this issue because we haven't been using `-Z no-trans` in a while.
