### ISSUE TITLE
Get "required-features" for target and set them

### ISSUE THREAD

**Issue by little-arhat** [flycheck/flycheck-rust#68]
Since it's currently impossible to define additional dependencies for a binary, some projects use workaround with `required-features` ([link](https://github.com/rust-lang/cargo/issues/1982#issuecomment-288537363)). To build such target one need to provide these required features:

```
cargo build --bin pwm
error: target `pwm` in package `proving_ground` requires the features: `with_device`
Consider enabling them by passing e.g. `--features="with_device"`
```

`flycheck-rust` should extract `required-features` and configure `rust-cargo` checker to use it.
`rust-cargo` will have to be extended as well to support `--features` flag, I guess?

**Comment by little-arhat** [comment]
https://github.com/rust-lang/cargo/pull/5902#event-1801344680 -- pull request adding `required-features` to `cargo metadata` output has been merged.

**Comment by fmdkdd** [comment]
That was quick!  Do you want to make the PR that extracts the `required-features` field as well?

**Comment by little-arhat** [comment]
@fmdkdd here is my attempt: https://github.com/flycheck/flycheck-rust/pull/69. Not sure it's the best solution (I had to fix all the tests), so feel free to fix, abandon or suggest a better way %)
