### ISSUE TITLE
Support for projects where there is neither a src/lib.rs nor a src/main.rs file

### ISSUE THREAD

**Issue by ane** [flycheck/flycheck-rust#7]
The `[lib]` directive lets you specify a custom path for the library root. 

If you use the [cargo](https://github.com/rust-lang/cargo/tree/master/src) project as an example, it's structured as follows:

```
.
├── bin
├── cargo
│   ├── core
│   │   └── resolver
│   ├── ops
│   │   └── cargo_rustc
│   ├── sources
│   │   └── git
... └── util
```

There is no `src/main.rs` or `src/lib.rs`.

The actual executable is in `src/bin/cargo.rs`, and the library itself is in `src/cargo/lib.rs`. If you load this project with racer, it will work fine when you edit anything in the `bin` folder (because of [this](https://github.com/flycheck/flycheck-rust/blob/master/flycheck-rust.el#L45) line), and the project root will be correctly set.

But if you open anything in `src/cargo`, it will try to set [here](https://github.com/flycheck/flycheck-rust/blob/master/flycheck-rust.el#L93) the fallback file to either `src/lib.rs` or `src/main.rs`, and Flycheck will not work when the source checking is complete. 

Some potential fixes I've thought about:

* Look for the closest `lib.rs` for the current file, if such exists. Then find the root directory from here. 
* Actually parse the `Cargo.toml` and get the lib.rs file from there.

**Comment by lunaryorn** [comment]
If you can implement a good workaround and open a pull request, I'll merge it, but I won't fix this myself.  I'm waiting for Cargo to provide an interface to export the project settings.  Once it's there, this library will just call Cargo and then set the corresponding flags, which will fix this and related issues.  See #8 to track the progress, but it's effectively block by Cargo upstream.

Closing, in favor of #8.
