### ISSUE TITLE
change target directory

### ISSUE THREAD

**Issue by wookietreiber** [flycheck/flycheck-rust#72]
Using `cargo` on the command line, I can change the target directory, e.g.:

```bash
cargo test --target-dir /tmp/project-name
```

Is it possible to change the target directory with **flycheck-rust** and if so how?

---

**Note:** I would like to do this to reduce the writes to my disk because it's an SSD and `/tmp` is a **tmpfs**.

**Note:** I do not want to set `target-dir` in `Cargo.toml` because I don't want to add this to version control.

**Comment by wookietreiber** [comment]
@fmdkdd Thanks, using `.dir-locals.el` works!

**Comment by fmdkdd** [comment]
:+1:
