### ISSUE TITLE
CARGO_HOME?

### ISSUE THREAD

**Issue by einsweniger** [flycheck/flycheck-rust#77]
flycheck-rust is not using the CARGO_HOME environment variable to find the `cargo` command, but I think it should.
I'd also think that `$CARGO_HOME/bin/cargo`, should take precedence over the `$PATH/cargo` executable.

Might be wrong, tho :D

**Comment by fmdkdd** [comment]
I don't have a strong opinion either way.  My setup has `cargo` on `$PATH`, and I guess you would want to add `$CARGO_HOME` to `$PATH` in order to use it outside of Emacs. In which case, `flycheck-rust` would pick the right binary.  Or is there a use-case I am missing?

**Comment by einsweniger** [comment]
I've given it more thought and you might be right, seems I'm kindof fighting windmills since many things expect cargo to be in `$PATH` or even hardcoded have it hardcoded to `.cargo/bin/cargo`. Since this is giving me more problems than it's worth having it not in `~/.cargo` and in `$PATH`. Seems like a 'me' problem :P
Sorry for the noise :D
